name: binder demo

on:
  push:
    branches:
      - main

jobs:
  repo2docker:
    runs-on: ubuntu-latest
    steps:
    - name: Cache the demo on mybinder.org
      uses: jupyterhub/repo2docker-action@master
      with:
        NO_PUSH: true
        MYBINDERORG_TAG: ${{ github.event.ref }}
